### ISSUE TITLE
demo.py cannot show result

### ISSUE THREAD

**Issue by ujsyehao** [Fang-Haoshu/RMPE#3]
when I run python examples/demo.py, the program can work normally:
![38](https://user-images.githubusercontent.com/17454232/35839859-babfaf5e-0b2d-11e8-8bdd-289e92cf081b.png)
but cannot show the result, Figure 1 is empty:
![39](https://user-images.githubusercontent.com/17454232/35839883-d1a89c26-0b2d-11e8-97e6-b9158f43c94c.png)

I have some extra information to provide:

- run "make runtest -j8", it has an error `PC: @     0x7f0d5cb2157f caffe::SpatialTransformerLayer<>::Backward_gpu()`,  I investigate the error, the implementation of SpatialTransformer layer cause the problem.

- run "jupyter notebook examples/rmpe/Regional\ Multi-person\ Pose\ Estimation.ipynb", it has error **the server cannot work**, the problem is my system problem, I cannot use jupyter.

Thank you in advance @Fang-Haoshu

**Comment by Fang-Haoshu** [comment]
It's weird...Can you try to store the image instead of drawing it? Like using plt.savefig()

**Comment by ujsyehao** [comment]
Hi, when I add plt.savefig(path) after plt.draw(), it can show the correct result, but I do not know the reason. Can you tell me the reason? Thank you in advance.

I have another confusion, I test the speed use sample images(demo.py provide):
![40](https://user-images.githubusercontent.com/17454232/35845208-499bf688-0b4c-11e8-8ef0-b8789c0ddff5.png)
average speed is 0.74 second but in Read.md
 >1.5s/frame

So I am confused it.

Is there any problem with my test method? Below is my test method code:
`start = time.time() ` 
`image = caffe.io.load_image(filename)`
`...`
`for i in xrange(len(preds)):`
             `__...`
`end = time.time()`
`print end - start`
`plt.draw()`
`plt.savefig('mypath')`
`time.sleep(1)`

**Comment by ujsyehao** [comment]
Hi, @Fang-Haoshu Do you have time to solve the problem?
Thank you in advance!

**Comment by Fang-Haoshu** [comment]
Hi, this is not problem. The time varies according to the number of people per image.

**Comment by ujsyehao** [comment]
I am sorry to bother you again, I am a newbie to pose estimation field and cannot figure out the time cost in RMPE/AlphaPose program.

As far as I know, use one image to test speed(only discuss batchsie=1 situation), 
**time cost = detection time  + pose estimation time**
 No matter how many people in a picture, it brings slight time cost difference in object detection(faster RCNN RPN network always output 300 proposals, then classify network operates on these 300 proposals), However, you say 

> The inference time depends on the number of persons in the image. On a Titan X GPU card, the inference time is about 0.2s per person.

So 0.2s = per person pose estimation time without people detection or 0.2s = per person pose estimation time plus people detection time?

**Comment by Fang-Haoshu** [comment]
human detection is fast and thus the average time for each person can be ignored.

**Comment by ujsyehao** [comment]
@Fang-Haoshu So 0.2s = per person pose estimation time without people detection?
