### ISSUE TITLE
A question about the Code of demo.py#L112 

### ISSUE THREAD

**Issue by lc4321** [Fang-Haoshu/RMPE#4]
Hi, when I debug the code of demo.py [#L112 ](https://github.com/Fang-Haoshu/RMPE/blob/master/examples/rmpe/demo.py#L112), the contens of scores_noNMS [#L122 ](https://github.com/Fang-Haoshu/RMPE/blob/master/examples/rmpe/demo.py#L122) is changed  automatically. Finally,  scores stored in scores_noNMS of each group is the same as that of the last group.  Is it right?

**Comment by Fang-Haoshu** [comment]
Oh, that's pretty weird. scores_noNMS should store each score_noNMS. Because I am using a append() function. Can you paste the debug log or any related information?

**Comment by lc4321** [comment]
When I adjusted the code, contents of scores_noNMS turned to normal.
    	    for i in range(0,16):
	        real_loc = transformBoxInvert([predictions[0,0,:,3*i+0],predictions[0,0,:,3*i+1]],xmin,ymin,xmax,ymax,64)
	        pred_noNMS.append(real_loc) 
	        aa=np.array([predictions[0,0,0,3*i+2]])
	        score_noNMS.append(aa)
	    preds_noNMS.append(pred_noNMS)
	    scores_noNMS.append(score_noNMS)

**Comment by Fang-Haoshu** [comment]
Thanks! I updated the code
